closetTracker/config/routes.rb
ClosetTracker::Application.routes.draw do
  resources :contacts , only: [:index, :create, :new, :show] do
    collection do
      get 'search'
    end
  end
  resources :outfits do
  end
  resources :start, only: :show do
  end
  root 'start#show'
  

  

end

closetTracker/app/models/contact.rb
class Contact < ActiveRecord::Base
  has_and_belongs_to_many :outfits

  def contact_matches text
  	if self.name.downcase.include? text.to_s
  		return true
  	end
  end
  validates :name, presence:true
end

closetTracker/app/models/outfit.rb
class Outfit < ActiveRecord::Base
  has_and_belongs_to_many :contacts
  default_scope order: 'created_at DESC'
  has_attached_file :photo, :path => ":rails_root/public/system/:attachment /:id/:style /:filename",
:url =>  "/system/:attachment/:id/:style/:filename", 
:styles  => { :small => "100x100#", :large => "500x500>" } 

  def create_outfit new_outfit
  	File.open(Rails.root.join('app', 'assets', 'images', new_outfit.original_filename), 'wb') do |file|
  	  file.write(new_outfit.read)
    end
  end
  validates :filename, presence:true
  validates :photo, :attachment_presence => true
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  
end

closetTracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

closetTracker/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end
  def new
  	@title = 'Create A New Contact'
  	@contact = Contact.new
  end
  def create
	  if params[:contact]
	    if Contact.find_by_name(params[:contact][:name])
		    redirect_to new_contact_path
	    else
	      @new_contact = Contact.create(contact_params(params[:contact]))
		    if @new_contact.save
		      redirect_to contact_path(@new_contact)
		    else
		      render :controller => :contacts, :action => :new
		    end			
	    end
	  end
  end
  def show
	  @contact = Contact.find(params[:id])
	  @title = Contact.find(params[:id]).name
  end
  def search
    @searched = params[:q]
    @results = []
    Contact.all.each do |c|
      if c.contact_matches @searched
        @results << [c.id, c.name]
      end
    end
    render :json => @results
  end
  private
  def contact_params(params)
	  return params.permit(:name)
  end	
end

closetTracker/app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  def index
    @all_outfits = Outfit.all
    @title = "All Your Outfits"
  end
  def new
    @title = "Upload A New Outfit"
    @contacts = Contact.all
    @outfit = Outfit.new
  end
  def create
    @outfit_to_make = Outfit.new(outfit_params)
    @outfit_to_make.contacts << Contact.find(params[:contacts])
    if @outfit_to_make.save	
      redirect_to :action => :index
    else
      redirect_to :action => :new
    end
  end
  private
  def outfit_params 
    params.require(:outfit).permit(:date_time, :photo, :contacts)
  end
end

closetTracker/app/controllers/start_controller.rb
class StartController < ApplicationController
	def show
	end
end

closetTracker/app/helpers/application_helper.rb
module ApplicationHelper
end

closetTracker/app/helpers/contacts_helper.rb
module ContactsHelper
end

closetTracker/app/helpers/outfits_helper.rb
module OutfitsHelper
end

closetTracker/app/views/contacts/index.html.erb
<div class = 'search-bar'>
	<input class = 'contact-search' type= 'text' id= 'search' placeholder= 'Search For A Contact'>
	    <span class='glyphicon glyphicon-search'></span>
	</input>
</div>
<h1 class = 'main-header'> Contacts <span class = 'btn pull-right add-button'><%= link_to '+', new_contact_path %></span></h1>
<table id = 'all-contact-index-table'>
	<% @contacts.each do |contact| %>
		<tr class = 'index-row'>
		    <td class = 'contact-index'><%= link_to contact.name, contact_path(contact) %><span class = 'glyphicon glyphicon-chevron-right pull-right'></span>
			</td>
		</tr>
	<% end %>
</table>
<table id = 'search-index-table'></table>

<script type='text/javascript'>
    //<![CDATA[
    new FindContacts('search', 'all-contact-index-table', 'search-index-table');
    //]]>
</script>

closetTracker/app/views/contacts/new.html.erb
<div class = 'main-header'>
  <h1 class = 'main-header no-search'> New Contact
  </h1>
</div>
<div class = 'form-div'>
	<%= form_for(@contact) do |form| %>
		  <span>Contact's Name:</span>
	 	  <span><%= form.text_field(:name) %></span>
	 	  <span><%= form.submit %></span>
	<% end %>
</div>

closetTracker/app/views/contacts/show.html.erb
<div class = 'main-header'>
  <h1 class = 'main-header no-search'>Outfits - <%= @contact.name %><span class = 'btn pull-right add-button'><%= link_to '+', new_outfit_path %></span></h1>
</div>
<% @contact.outfits.each do |outfit| %>
	<div class = 'outfit-photo'>
	  <%= image_tag outfit.filename %>
	  <p><%= outfit.date_time.getlocal %></p>
	</div>
<% end %>

closetTracker/app/views/layouts/application.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head> 
  <meta name="viewport" content = "width=device-width ,  user-scalable=no">
  <meta{name:"mobile-web-app-capable", content:"yes">
 	<title><%= @title %></title>
 	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" />
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css" />
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", :type => "text/javascript" %>
  </head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/#">
                 <span>OUTFITTRACK</span> 
            </a>
        </div>
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/contacts">Contacts</a>
                </li>
                <li>
                    <a href="/outfits">Outfits</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
    </nav>
  	<%= yield %>
  </body>
</html>

closetTracker/app/views/outfits/index.html.erb
<div class = 'main-header'>
  <h1 class = 'main-header no-search'> All Of Your Outfits<span class = 'btn pull-right add-button'><%= link_to '+', new_outfit_path %></span></h1>
</div>
<% if @all_outfits %> 
  <% @all_outfits.each do |outfit| %>
    <div class = 'outfit-photo'>
      <%= image_tag outfit.photo.url(:small) %>
      <p><%= outfit.date_time.getlocal %> </p>
    </div>
  <% end %>
<% end %>

closetTracker/app/views/outfits/new.html.erb
<div class = 'main-header'>
  <h1 class = 'main-header no-search'> Upload An Outfit </h1>
</div>
<div class = 'form-div'>
  <%= form_for Outfit.new, :html => { :multipart => true} do |f| %>
    <div class="field">
      <%= f.label 'Choose a Photo' %><br>
      <%= f.file_field :photo %>
      <%  @contacts.each do |c|  %>
    		<%= f.label c.name  %>
    		<%= check_box_tag "contacts[]", c.id %>
    	<% end %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

closetTracker/app/views/start/show.html.erb
<h1 class = 'main-header no-search'>WELCOME TO </h1>
<h1 class = 'main-header'>OUTFITTRACK </h1>
<div class = 'add-new-btn'>
	<%= link_to 'UPLOAD AN OUTFIT', new_outfit_path %>
</div>